// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://edvphmlnjprafdxcvmpo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVkdnBobWxuanByYWZkeGN2bXBvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NDUwOTMsImV4cCI6MjA2NjUyMTA5M30.0MwNoc-GxU5kUqK1-rfK1N11eyv71aIuTZBf9gmm5EA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);